import { TestBed } from '@angular/core/testing';

import { AuthService } from './auth.service';

describe('AuthService', () => {
  beforeEach(() => TestBed.configureTestingModule({}));

  it('should be created', () => {
    const service: AuthService = TestBed.get(AuthService);
    expect(service).toBeTruthy();
  });
});

// fhir-request.service hits the conformance statement

// we want to get our extension node, to get the auth and token urls
// hit the authorize endpoint with the following parameters
//  response_type, client_id, redirect_uri

// we then get back the auth code
// code: This parameter contains the authorization code generated by Epic.

// exchange the code for a token
// HTTP POST to the token service
// with these params grant_type,code, redirect_uri, client_id

// we then get back the token
// it contains a json object with the following
// access_token, token_type, expires_in, scope, patient

// and now we can get our data!
